
[client]
server_url = "http://localhost:8080" #necessary
connect = "http" 
adapter = "wl" #necessary
interval = 2000 #ms
X_selection = "clipboard" 
[server]
pull_history_size = 5
tmp_path = "./tmp" 
default_file_life = 300 #s