# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:
  
  base-env:
    runs-on: ubuntu-latest
    steps:
    - name: basic setup
      uses: actions/checkout@v4
      with:
        submodules: true
    - name: setup go
      uses: actions/setup-go@v4
      with:
        go-version-file: './go.mod'
    - name: setup node 
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: setup yarn
      run: |
        npm install --global yarn
        yarn --version
        
  compile:
    needs: "base-env"
    runs-on: ubuntu-latest
    steps:
    - name: compile frontend
      run: |
        make all
